# Generated by Django 6.0.3 on 2026-03-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('city', 'area_name')},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('-is_verified', '-availability_status', 'name')},
        ),
    ]
