# Generated by Django 6.0.3 on 2026-03-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=150)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('service_description', models.TextField(blank=True)),
                ('availability_status', models.BooleanField(default=True)),
                ('consent_to_contact', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='directory.worker')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='directory.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
