# Generated by Django 6.0.3 on 2026-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_workersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
