# Generated by Django 6.0.3 on 2026-03-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_worker_engagement_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='client_ip',
            field=models.CharField(blank=True, db_index=True, max_length=45),
        ),
    ]
