# Generated by Django 6.0.3 on 2026-03-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rating_client_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('area_name', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('service_description', models.TextField(blank=True)),
                ('availability_status', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.category')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='directory.worker')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
