# Generated by Django 6.0.3 on 2026-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_worker_update_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_keywords',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
