# Generated by Django 6.0.3 on 2026-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ml',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='name_ml',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
