# Generated by Django 6.0.3 on 2026-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_bilingual_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area_name_ml',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='city_ml',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
